# -----------------------------------------------------------------------------
# Base config: capD pretraining for our "base" bicaptioning model:
# ResNet-50 + (L = 1, H = 1024) transformer trained for 500K iterations.
# -----------------------------------------------------------------------------
RANDOM_SEED: 0
CUDNN_BENCHMARK: true
CUDNN_DETERMINISTIC: false

DATA:
  ROOT: "datasets/coco"
  TOKENIZER_MODEL: "datasets/vocab/coco17_10k.model"
  VOCAB_SIZE: 10000
  UNK_INDEX: 0
  SOS_INDEX: 1
  EOS_INDEX: 2
  MASK_INDEX: 3

  IMAGE_CROP_SIZE: 128 
  MAX_CAPTION_LENGTH: 30

  IMAGE_TRANSFORM_TRAIN:
    - "random_resized_crop"
    - "horizontal_flip"
    #- "color_jitter"
    - "normalize"

  IMAGE_TRANSFORM_VAL:
    - "smallest_resize"
    - "center_crop"
    - "normalize"

TEXT_ENCODER:
  NAME: "random"
  EMBEDDING_SIZE: 256
  FROZEN: false 

GENERATOR:
  NAME: "df"
  NOISE_SIZE: 100
  FEATURE_SIZE: 32

DISCRIMINATOR:
  NAME: "df"

  VISUAL:
    NAME: "df"
    FEATURE_SIZE: 32
    PRETRAINED: false 
    FROZEN: false

  LOGITOR:
    NAME: "df"


TRAIN:
  BATCH_SIZE: 64 
  NUM_ITERATIONS: 500000


GAN_LOSS: 
  TYPE: "hinge"
  D_LOSS_COMPONENT: "logit,magp"
  G_LOSS_COMPONENT: "logit"
  LOGIT_INPUT: "visual_features"

OPTIM:
  G:
    OPTIMIZER_NAME: "adam"
    VISUAL_LR: 0.0001
    BETAS: [0.0, 0.9]
    UPDATE_EMB: true 

  D:
    OPTIMIZER_NAME: "adam"
    VISUAL_LR: 0.0004
    BETAS: [0.0, 0.9]
    UPDATE_EMB: false