RANDOM_SEED: 100
AMP: false
CUDNN_BENCHMARK: true
CUDNN_DETERMINISTIC: false
DATA:
  IMAGE_CROP_SIZE: 256
  IMAGE_TRANSFORM_TEST:
  - smallest_resize
  - center_crop
  - normalize
  IMAGE_TRANSFORM_TRAIN:
  - random_resized_crop
  - horizontal_flip
  - normalize
  CAPTION_PER_IMAGE: 5
  UNK_INDEX: 0
  SOS_INDEX: 1
  EOS_INDEX: 2
  MASK_INDEX: 3
  MAX_CAPTION_LENGTH: 30
  ROOT: datasets/coco
  TOKENIZER_MODEL: datasets/vocab/coco14_10k.model
  VOCAB_SIZE: 10000
DISCRIMINATOR:
  NAME: capD #df #capD
  LOGITOR:
    H: 512
    NAME: df
  TEXTUAL:
    NAME: transdec_postnorm::L1_H512_A8_F2048
    CAPTION_BACKWARD: true 
    DECODER:
      BEAM_SIZE: 5
      MAX_DECODING_STEPS: 30
      NAME: beam_search
      NUCLEUS_SIZE: 0.9
    DROPOUT: 0.1
    FROZEN: false
    PRETRAINED: false
  VISUAL:
    NAME: df
    FEATURE_SIZE: 32
    DECODER: false
    FROZEN: false
    PRETRAINED: false
GAN_LOSS:
  CAP_COEFF: 1.0
  CAP_STOP_GRAD: false
  D_LOSS_COMPONENT: logit,magp,cap
  FA_FEATURE: visual_features
  GP: true
  G_LOSS_COMPONENT: logit
  LOGIT_INPUT: logit_features
  LOGIT_STOP_GRAD: false
  SLOW_CAPG: false
  TYPE: hinge
GENERATOR:
  NAME: df
  FEATURE_SIZE: 32
  NOISE_SIZE: 100
OPTIM:
  D:
    OPTIMIZER_NAME: adam
    VISUAL_LR: 0.0004
    TEXT_LR: 0.0004
    BETAS:
    - 0.0
    - 0.9
    CLIP_GRAD_NORM: 10.0
    SGD_MOMENTUM: 0.9
    LOOKAHEAD:
      ALPHA: 0.5
      STEPS: 5
      USE: false
    LR_DECAY_NAME: cosine
    LR_GAMMA: 0.1
    LR_STEPS: []
    NO_DECAY: .*textual.(embedding|transformer).*(norm.*|bias)
    UPDATE_EMB: false
    WARMUP_STEPS: 10000
    WEIGHT_DECAY: 0.0001
  G:
    OPTIMIZER_NAME: adam
    VISUAL_LR: 0.0001
    TEXT_LR: 0.0001
    BETAS:
    - 0.0
    - 0.9
    CLIP_GRAD_NORM: 10.0
    LOOKAHEAD:
      ALPHA: 0.5
      STEPS: 5
      USE: false
    LR_DECAY_NAME: cosine
    LR_GAMMA: 0.1
    LR_STEPS: []
    NO_DECAY: ''
    SGD_MOMENTUM: 0.9
    UPDATE_EMB: false
    WARMUP_STEPS: 10000
    WIEGHT_DECAY: 0.0001
TEXT_ENCODER:
  DIR: ''
  EMBEDDING_SIZE: 256
  FROZEN: true
  NAME: damsm
TRAIN:
  BATCH_SIZE: 24 
  NUM_ITERATIONS: 413880
