# -----------------------------------------------------------------------------
# Base config: capD pretraining for our "base" bicaptioning model:
# ResNet-50 + (L = 1, H = 1024) transformer trained for 500K iterations.
# -----------------------------------------------------------------------------

_BASE_: "_base_bicaptioning_R_50_L1_H1024.yaml"

DISCRIMINATOR:
  TEXTUAL:
    NAME: "transdec_postnorm::L1_H2048_A32_F8192"
  LOGITOR:
    H: 2048

GAN_LOSS:
  TYPE: "hinge"
  D_LOSS_COMPONENT: "logit,magp,cap"
  G_LOSS_COMPONENT: "logit,img_contra"
