# -----------------------------------------------------------------------------
# Base config: capD pretraining for our "base" bicaptioning model:
# ResNet-50 + (L = 1, H = 1024) transformer trained for 500K iterations.
# -----------------------------------------------------------------------------

_BASE_: "_base_bicaptioning_R_50_L1_H1024.yaml"

TEXT_ENCODER:
  NAME: "damsm" #"capD"
  EMBEDDING_SIZE: 256 #2048 
  FROZEN: True

GENERATOR:
  NAME: "df"
  NOISE_SIZE: 100
  FEATURE_SIZE: 32

DISCRIMINATOR:
  NAME: "capD"
  VISUAL:
    NAME: "df"
    DECODER: true
    FEATURE_SIZE: 32
    PRETRAINED: False
    FROZEN: False
  TEXTUAL:
    NAME: "transdec_postnorm::L1_H2048_A32_F8192"
  LOGITOR:
    NAME: "df"
    H: 2048

GAN_LOSS:
  TYPE: "hinge"
  D_LOSS_COMPONENT: "logit,magp" #,img_rec
  G_LOSS_COMPONENT: "logit" #,img_contra
  LOGIT_INPUT: "visual_features"
  LOGIT_STOP_GRAD: False
  FA_FEATURE: "visual_features"

OPTIM:
  G:
    OPTIMIZER_NAME: "adam"
    VISUAL_LR: 0.0001
    TEXT_LR: 0.0001
    UPDATE_EMB: False

  D:
    OPTIMIZER_NAME: "adam"
    VISUAL_LR: 0.0004
    TEXT_LR: 0.0004
    UPDATE_EMB: False
